/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

import cci.GerenciadorCIH;
import cdp.Materiais;
import cdp.Venda;

/**
 *
 * @author Anderson
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private GerenciadorCIH gerCCI;
    private Venda venda;
    private Materiais mate;
    private Boolean flag;

    
    public JFramePrincipal(java.awt.Frame parent,boolean modal, GerenciadorCIH ger,Boolean flag) {
        gerCCI = ger;
        initComponents();
        this.flag = flag;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrarClienteFornercedor = new javax.swing.JMenuItem();
        JMCadastrarMateriais = new javax.swing.JMenuItem();
        JMCadastrarVeiculo = new javax.swing.JMenuItem();
        JMCadastrarServico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMPesquisarCliente = new javax.swing.JMenuItem();
        JMPesquisarPedido = new javax.swing.JMenuItem();
        JMPesquisarMateriais = new javax.swing.JMenuItem();
        JMPesquisarServico = new javax.swing.JMenuItem();
        JMPesquisarVeiculo = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.red);
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        CadastrarClienteFornercedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N
        CadastrarClienteFornercedor.setText("Pessoas");
        CadastrarClienteFornercedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteFornercedorActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarClienteFornercedor);

        JMCadastrarMateriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        JMCadastrarMateriais.setText("Materiais");
        JMCadastrarMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastrarMateriaisActionPerformed(evt);
            }
        });
        jMenu1.add(JMCadastrarMateriais);

        JMCadastrarVeiculo.setText("Veiculo");
        JMCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastrarVeiculoActionPerformed(evt);
            }
        });
        jMenu1.add(JMCadastrarVeiculo);

        JMCadastrarServico.setText("Serviço");
        JMCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastrarServicoActionPerformed(evt);
            }
        });
        jMenu1.add(JMCadastrarServico);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pesquisar");

        JMPesquisarCliente.setText("Cliente");
        JMPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarCliente);

        JMPesquisarPedido.setText("Pedido");
        JMPesquisarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarPedidoActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarPedido);

        JMPesquisarMateriais.setText("Materiais");
        JMPesquisarMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarMateriaisActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarMateriais);

        JMPesquisarServico.setText("Serviço");
        JMPesquisarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarServicoActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarServico);

        JMPesquisarVeiculo.setText("Veiculo");
        JMPesquisarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarVeiculoActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarVeiculo);

        menuFornecedor.setText("Fornecedor");
        menuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(menuFornecedor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void CadastrarClienteFornercedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteFornercedorActionPerformed
        gerCCI.janelaCadCliente();
    }//GEN-LAST:event_CadastrarClienteFornercedorActionPerformed

    private void JMCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCadastrarServicoActionPerformed
        //gerCCI.janelaCadServico();
    }//GEN-LAST:event_JMCadastrarServicoActionPerformed

    private void JMCadastrarMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCadastrarMateriaisActionPerformed
        gerCCI.janelaCadMateriais();
    }//GEN-LAST:event_JMCadastrarMateriaisActionPerformed

    private void JMCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCadastrarVeiculoActionPerformed
       // gerCCI.janelaCadVeiculos();
    }//GEN-LAST:event_JMCadastrarVeiculoActionPerformed

    private void JMPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarClienteActionPerformed
       // gerCCI.janelaPesqCliente();
    }//GEN-LAST:event_JMPesquisarClienteActionPerformed

    private void JMPesquisarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarPedidoActionPerformed
      // gerCCI.janelaPesqPedido();
    }//GEN-LAST:event_JMPesquisarPedidoActionPerformed

    private void JMPesquisarMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarMateriaisActionPerformed
      // gerCCI.janelaPesqMaterial();
    }//GEN-LAST:event_JMPesquisarMateriaisActionPerformed

    private void JMPesquisarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarServicoActionPerformed
      // gerCCI.janelaPesqServico();
    }//GEN-LAST:event_JMPesquisarServicoActionPerformed

    private void JMPesquisarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarVeiculoActionPerformed
      // gerCCI.janelaPesqVeiculo();
    }//GEN-LAST:event_JMPesquisarVeiculoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
     
    }//GEN-LAST:event_formComponentShown

    private void menuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedorActionPerformed
         gerCCI.janelaPesqFor();
    }//GEN-LAST:event_menuFornecedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarClienteFornercedor;
    private javax.swing.JMenuItem JMCadastrarMateriais;
    private javax.swing.JMenuItem JMCadastrarServico;
    private javax.swing.JMenuItem JMCadastrarVeiculo;
    private javax.swing.JMenuItem JMPesquisarCliente;
    private javax.swing.JMenuItem JMPesquisarMateriais;
    private javax.swing.JMenuItem JMPesquisarPedido;
    private javax.swing.JMenuItem JMPesquisarServico;
    private javax.swing.JMenuItem JMPesquisarVeiculo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuFornecedor;
    // End of variables declaration//GEN-END:variables
}
