/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

import cci.GerenciadorCIH;
import cdp.Materiais;
import cdp.Venda;

/**
 *
 * @author Anderson
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private final GerenciadorCIH gerCCI;


    
    public JFramePrincipal(java.awt.Frame parent,boolean modal, GerenciadorCIH ger,Boolean flag) {
        gerCCI = ger;
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrarClienteFornercedor = new javax.swing.JMenuItem();
        JMCadastrarMateriais = new javax.swing.JMenuItem();
        JMCadastrarVeiculo = new javax.swing.JMenuItem();
        JMCadastrarServico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMPesquisarCliente = new javax.swing.JMenuItem();
        JMPesquisarMateriais = new javax.swing.JMenuItem();
        JMPesquisarServico = new javax.swing.JMenuItem();
        JMPesquisarVeiculo = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(221, 65, 67));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tecluz.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 304));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Cadastro");

        CadastrarClienteFornercedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N
        CadastrarClienteFornercedor.setText("Pessoas");
        CadastrarClienteFornercedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteFornercedorActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarClienteFornercedor);

        JMCadastrarMateriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        JMCadastrarMateriais.setText("Materiais");
        JMCadastrarMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastrarMateriaisActionPerformed(evt);
            }
        });
        jMenu1.add(JMCadastrarMateriais);

        JMCadastrarVeiculo.setText("Veiculo");
        JMCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastrarVeiculoActionPerformed(evt);
            }
        });
        jMenu1.add(JMCadastrarVeiculo);

        JMCadastrarServico.setText("Serviço");
        JMCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastrarServicoActionPerformed(evt);
            }
        });
        jMenu1.add(JMCadastrarServico);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Pesquisar");

        JMPesquisarCliente.setText("Cliente");
        JMPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarCliente);

        JMPesquisarMateriais.setText("Materiais");
        JMPesquisarMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarMateriaisActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarMateriais);

        JMPesquisarServico.setText("Serviço");
        JMPesquisarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarServicoActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarServico);

        JMPesquisarVeiculo.setText("Veiculo");
        JMPesquisarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPesquisarVeiculoActionPerformed(evt);
            }
        });
        jMenu2.add(JMPesquisarVeiculo);

        menuFornecedor.setText("Fornecedor");
        menuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(menuFornecedor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void CadastrarClienteFornercedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteFornercedorActionPerformed
        gerCCI.janelaCadCliente();
    }//GEN-LAST:event_CadastrarClienteFornercedorActionPerformed

    private void JMCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCadastrarServicoActionPerformed
        gerCCI.janelaCadServico();
    }//GEN-LAST:event_JMCadastrarServicoActionPerformed

    private void JMCadastrarMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCadastrarMateriaisActionPerformed
        gerCCI.janelaCadMateriais();
    }//GEN-LAST:event_JMCadastrarMateriaisActionPerformed

    private void JMCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCadastrarVeiculoActionPerformed
        gerCCI.janelaCadVeiculos();
    }//GEN-LAST:event_JMCadastrarVeiculoActionPerformed

    private void JMPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarClienteActionPerformed
        gerCCI.janelaPesqCliente();
    }//GEN-LAST:event_JMPesquisarClienteActionPerformed

    private void JMPesquisarMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarMateriaisActionPerformed
       gerCCI.janelaPesqMaterial();
    }//GEN-LAST:event_JMPesquisarMateriaisActionPerformed

    private void JMPesquisarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarServicoActionPerformed
       gerCCI.janelaPesqServico();
    }//GEN-LAST:event_JMPesquisarServicoActionPerformed

    private void JMPesquisarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPesquisarVeiculoActionPerformed
       gerCCI.janelaPesqVeiculo();
    }//GEN-LAST:event_JMPesquisarVeiculoActionPerformed

    private void menuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedorActionPerformed
       gerCCI.janelaPesqFor();
    }//GEN-LAST:event_menuFornecedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarClienteFornercedor;
    private javax.swing.JMenuItem JMCadastrarMateriais;
    private javax.swing.JMenuItem JMCadastrarServico;
    private javax.swing.JMenuItem JMCadastrarVeiculo;
    private javax.swing.JMenuItem JMPesquisarCliente;
    private javax.swing.JMenuItem JMPesquisarMateriais;
    private javax.swing.JMenuItem JMPesquisarServico;
    private javax.swing.JMenuItem JMPesquisarVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuFornecedor;
    // End of variables declaration//GEN-END:variables
}
